Repository andrewdimmer/calendar-condenser, pull requests merged in 2019-10, with the labels that each got.

#1 docs(front-end-web): Added README
  front-end-web/README.md
Labels: documentation

#9 feat(front-end-web): Updated types and added state handlers
  front-end-web/src/@Types/index.d.ts
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/scripts/googleScripts.ts
Labels: enhancement

#6 feat(ExportPage): Added export button and text field
  front-end-web/src/Components/Pages/ExportPage.tsx
Labels: enhancement

#5 feat(SuccessPage): Added check for stage
  front-end-web/package-lock.json
  front-end-web/package.json
  front-end-web/src/Components/Pages/SuccessPage.tsx
Labels: enhancement

#12 feat: Added authentication!
  front-end-web/public/auth.html
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/scripts/googleScripts.ts
  functions/package-lock.json
  functions/package.json
  functions/src/authHandlers.ts
  functions/src/index.ts
Labels: enhancement

#13 feat: Added a Privacy Policy
  front-end-web/src/Components/Content/PrivacyPolicy.tsx
  front-end-web/src/Components/Content/index.ts
  front-end-web/src/Components/Pages/MainPage.tsx
Labels: enhancement

#11 Update SelectionPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
Labels: enhancement

#14 feat(front-end-web): Added Initial Loader and Loading Page
  front-end-web/src/Components/Pages/LoadingPage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
  front-end-web/src/scripts/googleScripts.ts
Labels: bug, enhancement

#15 feat(front-end-web): Main Page Flow Shows Stages Sequentially
  front-end-web/src/Components/Pages/ExportPage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
Labels: enhancement
