Repository andrewdimmer/calendar-condenser, pull requests merged in 2019-11, with the labels that each got.

#20 fix(auth): Authorization now gets the refresh token properly.
  front-end-web/.gitignore
  front-end-web/package-lock.json
  front-end-web/package.json
  front-end-web/public/auth.html
  front-end-web/src/Components/Pages/ExportPage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/scripts/firebaseConfig.ts
  front-end-web/src/scripts/googleScripts.ts
  front-end-web/src/scripts/index.ts
  functions/src/authHandlers.ts
  functions/src/index.ts
Labels: bug

#21 feat: Given a refresh token, can now get and display calendars
  front-end-web/src/@Types/index.d.ts
  front-end-web/src/Components/Layouts/NavBar.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
  front-end-web/src/Styles/theme.ts
  front-end-web/src/scripts/googleScripts.ts
  functions/src/calendarListHandlers.ts
Labels: enhancement

#23 feat(front-end-web): Added Firebase Login
  front-end-web/package-lock.json
  front-end-web/package.json
  front-end-web/src/Components/Pages/ExportPage.tsx
  front-end-web/src/Components/Pages/LoginPage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
  front-end-web/src/Components/Pages/index.ts
Labels: enhancement

#24 Camron styles homepage
  front-end-web/package-lock.json
  front-end-web/src/Components/Layouts/NavBar.tsx
  front-end-web/src/Components/Pages/AuthorizationPage.tsx
  front-end-web/src/Components/Pages/ExportPage.tsx
  front-end-web/src/Components/Pages/HomePage.tsx
  front-end-web/src/Components/Pages/LoadingPage.tsx
  front-end-web/src/Components/Pages/LoginPage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
  front-end-web/src/Components/Pages/SuccessPage.tsx
  front-end-web/src/Components/Pages/index.ts
  front-end-web/src/Styles/index.ts
Labels: enhancement

#25 Camron styles homepage
  front-end-web/src/Components/Pages/HomePage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/index.ts
Labels: bug

#27 feat: added database
  front-end-web/src/scripts/databaseScripts.ts
  functions/package-lock.json
  functions/package.json
  functions/src/databaseHandler.ts
  functions/src/firebaseConfig.ts
  functions/src/index.ts
Labels: enhancement

#32 BREAKING CHANGE: OAuth Tokens Stored in Database, and Restore State from Cookie
  front-end-web/package-lock.json
  front-end-web/public/auth.html
  front-end-web/src/@Types/index.d.ts
  front-end-web/src/Components/Layouts/NavBar.tsx
  front-end-web/src/Components/Layouts/Notifications.tsx
  front-end-web/src/Components/Layouts/index.ts
  front-end-web/src/Components/Pages/AuthorizationPage.tsx
  front-end-web/src/Components/Pages/ExportPage.tsx
  front-end-web/src/Components/Pages/HomePage.tsx
  front-end-web/src/Components/Pages/LoginPage.tsx
  front-end-web/src/Components/Pages/MainPage.tsx
  front-end-web/src/Components/Pages/SelectionPage.tsx
  front-end-web/src/Components/Pages/SuccessPage.tsx
  front-end-web/src/scripts/calendarScripts.ts
  front-end-web/src/scripts/databaseScripts.ts
  front-end-web/src/scripts/googleScripts.ts
  front-end-web/src/scripts/index.ts
  functions/package-lock.json
  functions/package.json
  functions/src/authHandlers.ts
  functions/src/calendarListHandlers.ts
  functions/src/databaseHandler.ts
Labels: bug, documentation, enhancement
